# Font configuration
font_family      Lilex Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12

# Options
enable_audio_bell no
scrollback_lines 500 
url_style straight
tab_bar_style powerline

background_opacity 0.95

background_tint 0.975

allow_remote_control socket
listen_on unix:/tmp/kitty-{kitty_pid}

# Import the theme
include themes/noctalia.conf
