color0 #232130
color1 #fd4663
color2 #918bc1
color3 #9e7eb4
color4 #b47eae
color5 #b0acd3
color6 #c2aed0
color7 #f2f2f3
color8 #676574
color9 #fd4663
color10 #918bc1
color11 #9e7eb4
color12 #b47eae
color13 #b0acd3
color14 #c2aed0
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #1b1a23
background            #1b1a23
foreground            #f2f2f3
selection_foreground  #b0afb6
selection_background  #232130
active_border_color   #918bc1
inactive_border_color #232130
url_color             #918bc1

active_tab_foreground   #1c1b22
active_tab_background   #918bc1
inactive_tab_foreground #b0afb6
inactive_tab_background #232130
cursor_trail_color      #b0afb6
