color0 #24223a
color1 #ed7f90
color2 #78ba87
color3 #dfb67c
color4 #83abe9
color5 #ba9add
color6 #7fbbd8
color7 #000000
color8 #24223a
color9 #ed7f90
color10 #78ba87
color11 #dfb67c
color12 #83abe9
color13 #ba9add
color14 #7fbbd8
color15 #000000

cursor                #404c5c
cursor_text_color     #1e1c30
background            #1e1c30
foreground            #edebed
selection_foreground  #edebed
selection_background  #6a63a0
active_border_color   #7fbbd8
inactive_border_color #2a2843
url_color             #7fbbd8

active_tab_foreground   #24223a
active_tab_background   #7fbbd8
inactive_tab_foreground #edebed
inactive_tab_background #2a2843
cursor_trail_color      #edebed
